version: "3.7"

services:
  app-topic-5:
    image: alcardi/java-academy-topic-5
    ports:
      - 8080:8080
    environment:
      DEPLOY_PROFILE: prod
  mysql:
    image: alcardi/mydatabase-custom-image
    volumes:
      - myDataBase_volume:/var/lib/mysql
    ports:
      - 8050:3306
    environment:
      MYSQL_ROOT_PASSWORD: 14256958

volumes:
  myDataBase_volume: